SELECT
    A.CAR_ID AS CAR_ID,
    IFNULL(B.AVAILABILITY, "대여 가능") AS AVAILABILITY
FROM
(
    SELECT
        HIS.CAR_ID AS CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
    GROUP BY HIS.CAR_ID
    ORDER BY HIS.CAR_ID DESC
) A
LEFT JOIN
(
    SELECT
        HIS.CAR_ID AS CAR_ID,
        "대여중" AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
    WHERE DATE_FORMAT(HIS.START_DATE, "%Y-%m-%d") <= '2022-10-16'
    AND '2022-10-16' <= DATE_FORMAT(HIS.END_DATE, "%Y-%m-%d")
) B ON A.CAR_ID = B.CAR_ID;